import CookiePreferencesLink from "@/components/CookiePreferencesLink";
export default function Page(){return <><section className="pagehero"><div className="wrap"><div className="eyebrow light">Informação legal</div><h1>Política de Cookies</h1><p>Informação sobre cookies, armazenamento local e preferências de privacidade neste website.</p></div></section><section className="section legalPage"><div className="wrap">
<h2>1. O que são cookies</h2><p>Cookies são pequenos ficheiros ou identificadores que podem ser armazenados no equipamento do utilizador durante a navegação. Tecnologias semelhantes, como o armazenamento local do navegador, podem guardar preferências necessárias ao funcionamento de uma interface.</p>
<h2>2. O que utilizamos atualmente</h2><p>Nesta versão do website não são utilizados cookies de publicidade, perfilagem ou análise estatística. É utilizado armazenamento local estritamente necessário para guardar preferências escolhidas pelo utilizador, como a língua e a decisão relativa a cookies. Estas preferências não são utilizadas para publicidade comportamental.</p>
<h2>3. Categorias</h2><div className="legalTable"><div><strong>Necessários</strong><span>Funcionamento, segurança e conservação das preferências solicitadas pelo utilizador.</span><span>Não requerem consentimento quando estritamente necessários.</span></div><div><strong>Análise</strong><span>Medição de utilização e desempenho.</span><span>Não utilizados atualmente.</span></div><div><strong>Marketing</strong><span>Publicidade, perfilagem ou acompanhamento entre serviços.</span><span>Não utilizados atualmente.</span></div></div>
<h2>4. Consentimento</h2><p>Cookies ou tecnologias opcionais que venham a ser introduzidos não deverão ser ativados antes de uma escolha válida do utilizador. O utilizador pode aceitar ou rejeitar cookies opcionais e alterar posteriormente a sua preferência.</p><p><CookiePreferencesLink/></p>
<h2>5. Serviços e ligações externas</h2><p>O website contém ligações para serviços externos, incluindo Facebook e WhistleOn. Ao seguir uma ligação externa, o utilizador passa a estar sujeito às políticas e tecnologias do respetivo terceiro. Uma simples ligação não autoriza a Tamanho Eficaz a colocar cookies desse terceiro no equipamento do visitante.</p>
<h2>6. Gestão no navegador</h2><p>O utilizador pode também apagar ou bloquear cookies e armazenamento local através das definições do navegador. A eliminação das preferências locais poderá fazer com que o website volte a solicitar a escolha de cookies ou de idioma.</p>
<h2>7. Alterações</h2><p>Se forem introduzidas ferramentas de análise, marketing ou outros serviços não essenciais, esta política e o mecanismo de consentimento deverão ser atualizados antes da respetiva ativação.</p>
<h2>8. Contacto</h2><p>Questões sobre privacidade ou cookies podem ser enviadas para <strong>geral@tamanhoeficaz.pt</strong>.</p><p><strong>Última atualização: 30 de setembro de 2026.</strong></p>
</div></section></>}
