"use client";
import {useEffect} from "react";

const dict:Record<string,string>={
"Empresa":"Company",
"Serviços":"Services",
"Projetos":"Projects",
"Internacional":"International",
"Notícias":"News",
"Carreiras":"Careers",
"Contactos":"Contacts",
"Pedir proposta":"Request a quote",
"Contacte-nos":"Contact us",
"Sobre nós":"About us",
"Soluções":"Solutions",
"Privacidade":"Privacy",
"Cookies":"Cookies",
"Canal de denúncias":"Whistleblowing channel",
"Site desenvolvido por":"Site developed by",
"NOVOS DESAFIOS":"NEW CHALLENGES",
"Tem um projeto industrial em que podemos ajudar?":"Do you have an industrial project we can help with?",
"Manutenção industrial e indústria metalomecânica.":"Industrial maintenance and metalworking industry.",
"Atividade publicada em Portugal, Espanha, França e Bélgica.":"Published activity in Portugal, Spain, France and Belgium.",
"Desde 2019 · Indústria metalomecânica":"Since 2019 · Metalworking industry",
"Competência industrial sem fronteiras.":"Industrial expertise without borders.",
"Manutenção industrial, fabricação e equipas técnicas para projetos exigentes em Portugal e na Europa.":"Industrial maintenance, fabrication and technical teams for demanding projects in Portugal and across Europe.",
"Ver projetos":"View projects",
"Falar connosco":"Contact us",
"Fundação":"Founded",
"mercados europeus publicados":"published European markets",
"Empresa Gazela":"Gazelle Company",
"experiência divulgada":"published experience",
"CAPACIDADES":"CAPABILITIES",
"Especialistas na indústria metalomecânica":"Metalworking industry specialists",
"Serviços publicados pela Tamanho Eficaz, apresentados numa estrutura mais clara e orientada a clientes industriais.":"Services published by Tamanho Eficaz, presented in a clearer structure focused on industrial clients.",
"Conhecer capacidade →":"Explore capability →",
"INTERNACIONALIZAÇÃO":"INTERNATIONALISATION",
"Portugal. Espanha. França. Bélgica.":"Portugal. Spain. France. Belgium.",
"A empresa publica atividade nestes quatro mercados e aponta a internacionalização como um dos motores do seu crescimento.":"The company publishes activity in these four markets and identifies internationalisation as one of the drivers of its growth.",
"Presença internacional":"International presence",
"PORTEFÓLIO PUBLICADO":"PUBLISHED PORTFOLIO",
"Projetos em destaque":"Featured projects",
"Projeto":"Project",
"Galeria original publicada pela Tamanho Eficaz.":"Original gallery published by Tamanho Eficaz.",
"Explorar →":"Explore →",
"RECONHECIMENTO":"RECOGNITION",
"Empresa Gazela em dois anos consecutivos":"Gazelle Company for two consecutive years",
"Distinções referentes a 2023 e 2024, comunicadas pela empresa como reconhecimento do seu percurso de crescimento.":"Awards for 2023 and 2024, communicated by the company as recognition of its growth trajectory.",
"Ver notícias":"View news",
"NO TERRENO":"ON SITE",
"Pessoas, técnica e execução.":"People, expertise and execution.",
"Uma seleção de registos reais divulgados pela empresa, sem atribuir projeto ou cliente quando essa identificação não está confirmada.":"A selection of real records published by the company, without attributing a project or client where that identification is not confirmed.",
"Competências":"Capabilities",
"Serviços especializados":"Specialised services",
"Equipas e soluções técnicas para projetos de metalomecânica e manutenção industrial.":"Technical teams and solutions for metalworking and industrial maintenance projects.",
"Soldadura":"Welding",
"Serralharia":"Metal fabrication",
"Serralharia Mecânica":"Mechanical metalwork",
"Eletricidade":"Electrical",
"Tubistas":"Pipefitters",
"Operadores de Grua":"Crane operators",
"Conhecer serviço →":"Explore service →",
"Tem um projeto nesta área?":"Do you have a project in this area?",
"Fale connosco para analisarmos as necessidades do seu projeto.":"Contact us so we can assess your project requirements.",
"Qualidade, segurança e acompanhamento":"Quality, safety and support",
"Porquê escolher-nos":"Why choose us",
"Qualidade e Precisão":"Quality and precision",
"Equipa Especializada":"Specialist team",
"Cumprimento de Prazos":"On-time delivery",
"Segurança":"Safety",
"Soluções Personalizadas":"Tailored solutions",
"A empresa":"The company",
"Competência, confiança e crescimento sustentável":"Expertise, trust and sustainable growth",
"IDENTIDADE":"IDENTITY",
"Parcerias construídas para durar":"Partnerships built to last",
"Visão":"Vision",
"Valores":"Values",
"QUALIDADE E SEGURANÇA":"QUALITY AND SAFETY",
"Preparação técnica e prevenção":"Technical preparation and prevention",
"Política de Privacidade":"Privacy Policy",
"Política de Cookies":"Cookie Policy",
"Preferências de cookies":"Cookie preferences",
"Aceitar todos":"Accept all",
"Apenas necessários":"Necessary only",
"Gerir preferências":"Manage preferences",
"Guardar preferências":"Save preferences",
"Rejeitar opcionais":"Reject optional cookies",
"Serviço":"Service",
"Trabalho industrial Tamanho Eficaz":"Tamanho Eficaz industrial work",
"Onshore & Offshore":"Onshore & Offshore",
"Os nossos serviços incluem":"Our services include",
"Portefólio":"Portfolio",
"Os nossos trabalhos":"Our work",
"Projetos publicados pela Tamanho Eficaz, apresentados numa experiência visual mais forte e orientada ao contexto industrial.":"Projects published by Tamanho Eficaz, presented through a stronger visual experience focused on the industrial context.",
"Explorar projeto →":"Explore project →",
"Portefólio publicado":"Published portfolio",
"Galeria do projeto":"Project gallery",
"Selecione uma imagem para abrir a galeria. Pode navegar pelas setas ou pelo teclado.":"Select an image to open the gallery. Navigate using the arrows or keyboard.",
"Experiência além-fronteiras":"Experience across borders",
"A Tamanho Eficaz publica atividade em Portugal, Espanha, França e Bélgica, com projetos ligados à indústria e energia.":"Tamanho Eficaz publishes activity in Portugal, Spain, France and Belgium, with projects linked to industry and energy.",
"MERCADOS PUBLICADOS":"PUBLISHED MARKETS",
"Uma operação com dimensão europeia":"A European-scale operation",
"Em entrevista de 2024, Filipe Silva apontou Países Baixos e Alemanha como mercados pretendidos para expansão e destacou projetos ligados à energia onshore e offshore. Estes dois países são apresentados como ambição, não como presença já estabelecida.":"In a 2024 interview, Filipe Silva identified the Netherlands and Germany as target markets for expansion and highlighted projects linked to onshore and offshore energy. These two countries are presented as an ambition, not as an already established presence.",
"PARCERIAS":"PARTNERSHIPS",
"Experiência em cadeias industriais exigentes":"Experience in demanding industrial supply chains",
"A liderança identificou publicamente a Smulders Projects N.V. como um dos seus melhores clientes internacionais e relacionou essa colaboração com preparação em soldadura, desenho técnico e organização da fabricação.":"The company's leadership publicly identified Smulders Projects N.V. as one of its leading international clients and linked this cooperation to preparation in welding, technical drawing and fabrication organisation.",
"Projeto internacional":"International project",
"Mantenha-se a par":"Stay up to date",
"Reconhecimento, crescimento e atividade da Tamanho Eficaz.":"Recognition, growth and activity at Tamanho Eficaz.",
"Ler notícia →":"Read article →",
"← Todas as notícias":"← All news",
"Fale connosco":"Contact us",
"Estamos disponíveis para analisar o seu próximo projeto.":"We are available to assess your next project.",
"Segunda a Sexta: 08:00–17:00":"Monday to Friday: 08:00–17:00",
"Assunto":"Subject",
"Como podemos ajudar?":"How can we help?",
"Enviar mensagem":"Send message",
"Comercial":"Sales",
"Fale-nos do seu projeto":"Tell us about your project",
"Partilhe connosco as necessidades do projeto. A equipa poderá analisar o pedido e entrar em contacto consigo.":"Tell us about your project requirements. Our team can review your request and contact you.",
"Nome":"Name",
"Telefone":"Phone",
"Serviço pretendido":"Required service",
"Tubagem":"Pipework",
"País / Local do projeto":"Country / Project location",
"Descreva o projeto, necessidades, quantidades e prazo pretendido":"Describe the project, requirements, quantities and desired timeframe",
"Enviar pedido de proposta":"Submit quote request",
"Construa o futuro connosco":"Build the future with us",
"Qualificação, preparação técnica e segurança para responder a projetos industriais exigentes.":"Skills, technical preparation and safety for demanding industrial projects.",
"RECRUTAMENTO":"RECRUITMENT",
"Perfis técnicos":"Technical profiles",
"A presença pública da empresa inclui recrutamento de soldadores, serralheiros tubistas, operadores de calandra e outros perfis metalomecânicos. Na versão final, as vagas devem ser alimentadas apenas por anúncios confirmados e atuais.":"The company's public activity includes recruitment of welders, pipefitters, plate-rolling machine operators and other metalworking profiles. In the final version, vacancies should only be populated from confirmed and current job advertisements.",
"Recrutamento":"Recruitment",
"Área profissional":"Professional area",
"Operação de grua":"Crane operation",
"Experiência e disponibilidade":"Experience and availability",
"Enviar candidatura":"Submit application",
"Proteção de dados":"Data protection",
"Informação sobre tratamento de dados pessoais, formulários e candidaturas.":"Information on the processing of personal data, forms and applications.",
"O texto jurídico definitivo será alinhado com os processos, fornecedores e períodos de conservação efetivamente adotados pela Tamanho Eficaz antes da entrada em produção.":"The final legal text will be aligned with the processes, suppliers and retention periods effectively adopted by Tamanho Eficaz before the website goes into production.",
"Informação legal":"Legal information",
"Informação sobre a utilização de cookies e tecnologias semelhantes neste website.":"Information about the use of cookies and similar technologies on this website.",
"Cookies e armazenamento local":"Cookies and local storage",
"Na presente versão do website não são utilizados cookies de publicidade, perfilagem ou análise estatística. O site pode utilizar armazenamento local do navegador estritamente para guardar preferências da interface, nomeadamente o registo de que o aviso de privacidade e cookies já foi apresentado.":"This version of the website does not use advertising, profiling or analytics cookies. The site may use browser local storage strictly to save interface preferences, including whether the privacy and cookie notice has already been displayed.",
"Serviços externos":"External services",
"Algumas ligações podem encaminhar o utilizador para serviços externos, como Facebook, WhistleOn ou serviços de tradução. Esses serviços têm políticas de privacidade e cookies próprias, aplicáveis quando o utilizador os visita.":"Some links may direct users to external services such as Facebook or WhistleOn. Those services have their own privacy and cookie policies, which apply when users visit them.",
"Alterações futuras":"Future changes",
"Se forem introduzidas ferramentas de análise, marketing ou outros serviços que utilizem cookies não essenciais, o mecanismo de consentimento deverá ser atualizado antes da sua ativação.":"If analytics, marketing or other services using non-essential cookies are introduced, the consent mechanism must be updated before they are activated.",
"Contacto":"Contact",
"Para questões relacionadas com privacidade pode contactar a Tamanho Eficaz através de geral@tamanhoeficaz.pt.":"For privacy-related questions, contact Tamanho Eficaz at geral@tamanhoeficaz.pt.",
"Fundada em 2019, a Tamanho Eficaz é especializada em manutenção industrial e fabricação de projetos e fundações offshore, com atividade nacional e europeia.":"Founded in 2019, Tamanho Eficaz specialises in industrial maintenance and the fabrication of offshore projects and foundations, operating in Portugal and across Europe.",
"A missão publicada pela empresa assenta em relações de longo prazo baseadas na competência e confiança, reforçando a presença nos mercados nacional e internacional.":"The company's published mission is based on long-term relationships built on expertise and trust, strengthening its presence in domestic and international markets.",
"Conhecimento continuamente atualizado, crescimento sustentável e resposta aos novos desafios dos mercados.":"Continuously updated knowledge, sustainable growth and the ability to respond to new market challenges.",
"Motivação, eficiência e melhoria contínua, com foco na execução dos projetos dos clientes.":"Motivation, efficiency and continuous improvement, focused on delivering clients' projects.",
"Em entrevista, a liderança destacou formação, análise de risco, atualização dos processos de soldadura e preparação dos colaboradores em desenho técnico e organização da fabricação.":"In an interview, the company's leadership highlighted training, risk analysis, updated welding processes and employee preparation in technical drawing and fabrication organisation.",
"o site atual indica que a implementação estava em curso. A demo não apresenta a empresa como certificada enquanto o estado documental não for confirmado.":"the current website states that implementation was under way. This demo does not present the company as certified until the documentary status is confirmed.",
"Privacidade e cookies":"Privacy and cookies",
"Este site utiliza apenas armazenamento estritamente necessário ao funcionamento e às preferências da demonstração. Consulte a nossa":"This site only uses storage strictly necessary for operation and demo preferences. See our",
"Compreendi":"Understood",
"Soluções de soldadura para necessidades industriais e comerciais, executadas por equipas especializadas.":"Welding solutions for industrial and commercial requirements, delivered by specialist teams.",
"Fabricação, montagem, manutenção e reparação de soluções metálicas à medida.":"Fabrication, assembly, maintenance and repair of bespoke metal solutions.",
"Fabricação e montagem de componentes e estruturas para aplicações industriais.":"Fabrication and assembly of components and structures for industrial applications.",
"Soluções integradas de eletricidade e automação para instalações industriais.":"Integrated electrical and automation solutions for industrial facilities.",
"Instalação, montagem, manutenção, soldadura, inspeção e testes de sistemas de tubagem.":"Installation, assembly, maintenance, welding, inspection and testing of piping systems.",
"Operação e coordenação de movimentação de cargas em contexto industrial.":"Operation and coordination of load handling in industrial environments.",
"Prémio Empresas Gazela 2024":"Gazelle Company Award 2024",
"Prémio Empresas Gazela 2023":"Gazelle Company Award 2023",
"7 de julho de 2025":"7 July 2025",
"11 de julho de 2024":"11 July 2024",
"Tamanho Eficaz, Lda. recebe pelo segundo ano consecutivo o prémio GAZELA 2024.":"Tamanho Eficaz, Lda. receives the GAZELA 2024 award for the second consecutive year.",
"“A trajetória da empresa sempre foi marcada pela aposta na qualidade.”":"“The company's journey has always been marked by a commitment to quality.”",
"A nossa empresa é especializada em serviços de soldadura na área de metalomecânica, oferecendo soluções de alta qualidade e precisão para as necessidades industriais e comerciais dos nossos clientes. Com uma equipa de soldadores altamente qualificados e experientes, garantimos um serviço eficiente, seguro e conforme com as normas e padrões exigidos no mercado.":"We specialise in welding services for the metalworking industry, providing high-quality, precise solutions for our clients' industrial and commercial requirements. Our highly qualified and experienced welding teams deliver efficient, safe work in accordance with applicable standards.",
"A nossa empresa é líder em serviços de serralharia na área de metalomecânica, oferecendo soluções personalizadas e de alta qualidade para atender às diversas necessidades dos nossos clientes. Contamos com uma equipa de serralheiros altamente qualificados e experientes, prontos para realizar projetos de pequena, média e grande escala com excelência e profissionalismo.":"We provide metal fabrication services for the metalworking industry, delivering tailored, high-quality solutions for a wide range of client requirements. Our experienced teams are prepared for projects of different scales.",
"Na nossa empresa, somos especialistas em serviços de serralharia mecânica na área de metalomecânica, oferecendo soluções inovadoras e de alta qualidade para os mais diversos setores industriais. Com uma equipa de serralheiros mecânicos altamente qualificados e equipados com tecnologia de ponta, garantimos a execução precisa e eficiente de cada projeto.":"We specialise in mechanical metalwork for a wide range of industrial sectors, providing high-quality solutions delivered by qualified teams with modern equipment and a focus on precise, efficient execution.",
"A nossa empresa é especializada em serviços de eletricidade na área de metalomecânica, oferecendo soluções integradas e de alta qualidade para projetos industriais e comerciais. Contamos com uma equipa de eletricistas altamente qualificados e experientes, prontos para atender às necessidades específicas dos nossos clientes com eficiência e profissionalismo.":"We specialise in electrical services for the metalworking industry, providing integrated solutions for industrial and commercial projects through qualified and experienced electrical teams.",
"A nossa empresa é especialista em serviços de tubagem na área de metalomecânica, oferecendo soluções completas e de alta qualidade para projetos industriais e comerciais. Contamos com uma equipa de tubistas altamente qualificados e experientes, prontos para atender às necessidades específicas dos nossos clientes com eficiência e profissionalismo.":"We specialise in industrial piping services, providing complete solutions for industrial and commercial projects through qualified and experienced pipefitting teams.",
"A nossa empresa oferece serviços especializados de operadores de grua na área de metalomecânica, garantindo a movimentação segura e eficiente de cargas pesadas e materiais em projetos industriais e comerciais. Contamos com uma equipa de operadores de grua altamente qualificados e experientes.":"We provide specialist crane operator services for industrial and commercial projects, focused on the safe and efficient handling of heavy loads and materials by qualified and experienced operators.",
"Instalação de Sistemas de Tubagem":"Piping System Installation",
"Manutenção e Reparação de Tubagens":"Piping Maintenance and Repair",
"Montagem de Tubagem Industrial":"Industrial Piping Assembly",
"Inspeção e Testes de Tubagem":"Piping Inspection and Testing",
"Instalação de sistemas de tubagem para transporte de fluidos e gases em instalações industriais.":"Installation of piping systems for transporting fluids and gases in industrial facilities.",
"Manutenção e reparação destinadas a assegurar a durabilidade e a operação contínua dos sistemas.":"Maintenance and repair to support system durability and continuous operation.",
"Montagem de tubagem em fábricas, refinarias, centrais elétricas e outras instalações industriais.":"Piping assembly in factories, refineries, power plants and other industrial facilities.",
"Soldadura especializada em aço carbono, aço inoxidável, cobre e outros materiais.":"Specialist welding of carbon steel, stainless steel, copper and other materials.",
"Inspeções e testes dos sistemas de tubagem para verificação de segurança e qualidade.":"Inspection and testing of piping systems to verify safety and quality.",
"Fabricação e Montagem de Estruturas Metálicas":"Fabrication and Assembly of Steel Structures",
"Coberturas Metálicas":"Metal Roofing",
"Manutenção e Reparação":"Maintenance and Repair",
"Fabricação de Peças Sob Encomenda":"Custom Parts Fabrication",
"Montagem de Equipamentos Industriais":"Industrial Equipment Assembly",
"Manutenção e Reparação de Estruturas Metálicas":"Steel Structure Maintenance and Repair",
"Construção de Estruturas Metálicas Personalizadas":"Custom Steel Structures",
"Serviços de Usinagem e Torneamento":"Machining and Turning Services",
"Instalação e Manutenção de Sistemas Elétricos Industriais":"Industrial Electrical Systems Installation and Maintenance",
"Automação Industrial":"Industrial Automation",
"Iluminação Industrial":"Industrial Lighting",
"Segurança Elétrica":"Electrical Safety",
"Operação de Gruas de Torre e Móveis":"Tower and Mobile Crane Operation",
"Movimentação de Cargas Pesadas":"Heavy Load Handling",
"Montagem e Desmontagem de Gruas":"Crane Assembly and Disassembly",
"Planeamento e Coordenação de Operações":"Operations Planning and Coordination",
"Manutenção Preventiva e Corretiva":"Preventive and Corrective Maintenance",
"Experiência e Profissionalismo":"Experience and Professionalism",
"Experiência Comprovada":"Proven Experience",
"Tecnologia de Ponta":"Advanced Technology",
"Segurança e Conformidade":"Safety and Compliance",
"Atendimento Personalizado":"Personalised Service",
"Qualidade Superior":"High Quality",
"Compromisso com Prazos":"Commitment to Deadlines",
"Prazos Cumpridos":"On-time Delivery"
};
Object.assign(dict,{
"Indústria portuguesa com dimensão europeia":"Portuguese industry with a European reach",
"Constituída em 2019, a Tamanho Eficaz desenvolve atividade na metalomecânica, manutenção industrial e execução de soluções técnicas para projetos nacionais e internacionais.":"Established in 2019, Tamanho Eficaz operates in metalworking, industrial maintenance and the delivery of technical solutions for national and international projects.",
"PERFIL EMPRESARIAL":"COMPANY PROFILE",
"Com sede em Souselas, Coimbra, a Tamanho Eficaz, Lda. está ativa desde 9 de abril de 2019. O CAE principal atualmente publicado é 25530 — Maquinagem de metais, enquadrando uma atividade que a própria empresa apresenta de forma mais ampla na indústria metalomecânica e manutenção industrial.":"Based in Souselas, Coimbra, Tamanho Eficaz, Lda. has been active since 9 April 2019. Its currently published primary economic activity code is 25530 — Machining of metals, within a broader activity that the company presents in metalworking and industrial maintenance.",
"A presença pública da empresa inclui serviços de soldadura, serralharia, serralharia mecânica, eletricidade industrial, tubagem e operação de gruas, com atuação divulgada em Portugal, Espanha, França e Bélgica.":"The company's public offering includes welding, metal fabrication, mechanical metalwork, industrial electrical work, piping and crane operation, with activity published in Portugal, Spain, France and Belgium.",
"Constituição":"Established",
"NIPC":"Company tax ID",
"CAE principal":"Primary activity code",
"Sede":"Head office",
"ATIVIDADE":"ACTIVITY",
"Metalomecânica, manutenção e execução industrial":"Metalworking, maintenance and industrial execution",
"A comunicação institucional da empresa identifica a manutenção industrial e a fabricação de projetos e fundações offshore como áreas de especialização. Publicações mais recentes reforçam também a manutenção industrial, fundações onshore, estruturas metálicas e a qualificação das equipas.":"The company's institutional communications identify industrial maintenance and the fabrication of offshore projects and foundations as areas of specialisation. More recent publications also emphasise industrial maintenance, onshore foundations, steel structures and team qualification.",
"As especializações publicadas incluem metalomecânica, metalurgia, cimenteiras, estruturas metálicas e papeleiras, refletindo uma atuação transversal em ambientes industriais exigentes.":"Published specialisations include metalworking, metallurgy, cement plants, steel structures and the pulp and paper industry, reflecting cross-sector activity in demanding industrial environments.",
"MISSÃO · VISÃO · VALORES":"MISSION · VISION · VALUES",
"Crescimento sustentado por relações de longo prazo":"Sustainable growth built on long-term relationships",
"Missão":"Mission",
"Fomentar parcerias de longo prazo assentes na competência e confiança, reforçando a posição da empresa nos mercados nacional e internacional.":"Build long-term partnerships based on expertise and trust, strengthening the company's position in national and international markets.",
"Atualizar continuamente conhecimento e capacidade técnica, promovendo um crescimento sustentável e preparado para novos desafios de mercado.":"Continuously update knowledge and technical capability, promoting sustainable growth prepared for new market challenges.",
"Motivação, eficiência, melhoria contínua, proximidade com o cliente e foco na qualidade e segurança da execução.":"Motivation, efficiency, continuous improvement, customer proximity and a focus on quality and safe execution.",
"Portugal e Europa":"Portugal and Europe",
"A empresa publica atividade em Portugal, Espanha, França e Bélgica. A entrada nos mercados internacionais foi apontada pela própria liderança como um dos fatores diferenciadores do crescimento da Tamanho Eficaz.":"The company publishes activity in Portugal, Spain, France and Belgium. Its leadership has identified entry into international markets as one of the differentiating factors behind Tamanho Eficaz's growth.",
"Em comunicações públicas, a empresa referiu ainda os Países Baixos e a Alemanha como mercados pretendidos para expansão. Estes dois países são apresentados aqui como objetivo estratégico, e não como presença operacional confirmada.":"In public communications, the company has also identified the Netherlands and Germany as target markets for expansion. These two countries are presented here as strategic objectives, not as confirmed operational markets.",
"CRESCIMENTO E RECONHECIMENTO":"GROWTH AND RECOGNITION",
"Gazela 2023 e 2024":"Gazelle 2023 and 2024",
"A Tamanho Eficaz foi distinguida como Empresa Gazela da Região Centro relativamente a 2023 e voltou a integrar a lista de Empresas Gazela de 2024. A empresa associa este percurso à qualificação das equipas, proximidade com clientes, internacionalização e melhoria contínua.":"Tamanho Eficaz was recognised as a Gazelle Company in Portugal's Centro Region for 2023 and again joined the 2024 Gazelle Companies list. The company associates this trajectory with team qualification, customer proximity, internationalisation and continuous improvement.",
"Mais recentemente, a Tamanho Eficaz divulgou a sua presença na 20.ª edição do Millennium Portugal Exportador, enquadrando-a na estratégia de internacionalização, acompanhamento das tendências de mercado e desenvolvimento de soluções para parceiros e clientes.":"More recently, Tamanho Eficaz publicised its participation in the 20th Millennium Portugal Exportador, framing it within its internationalisation strategy, monitoring of market trends and development of solutions for partners and customers.",
"QUALIFICAÇÃO E SEGURANÇA":"SKILLS AND SAFETY",
"Equipas preparadas para projetos exigentes":"Teams prepared for demanding projects",
"Em entrevistas públicas, a liderança destaca a qualificação das equipas, formação especializada, análise de risco, preparação em soldadura, leitura e desenho técnico e organização da fabricação como fatores relevantes para a execução dos projetos.":"In public interviews, the company's leadership highlights team qualification, specialist training, risk analysis, welding preparation, technical drawing and fabrication organisation as relevant factors in project execution.",
"ISO 9001 e ISO 45001:":"ISO 9001 and ISO 45001:",
"Abrir menu":"Open menu",
"Fechar menu":"Close menu",
"Menu principal":"Main menu"
});
function translate(root:Node){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
 const nodes:Text[]=[]; let n; while(n=walker.nextNode()) nodes.push(n as Text);
 for(const t of nodes){const raw=t.nodeValue||"";const trimmed=raw.trim();if(dict[trimmed]) t.nodeValue=raw.replace(trimmed,dict[trimmed]);}
 const el=root instanceof Element?root:null; const scope=el?[el,...Array.from(el.querySelectorAll("input,textarea,option,[aria-label],[title],img"))]:Array.from(document.querySelectorAll("input,textarea,option,[aria-label],[title],img"));
 for(const x of scope as Element[]){for(const a of ["placeholder","aria-label","title","alt"]){const val=x.getAttribute(a);if(val&&dict[val])x.setAttribute(a,dict[val]);} if(x.tagName==="OPTION"){const txt=x.textContent?.trim()||"";if(dict[txt])x.textContent=dict[txt];}}
}

export default function EnglishOverlay(){useEffect(()=>{if((localStorage.getItem("te-lang")||"pt")==="en"){document.documentElement.lang="en";translate(document.body);const o=new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(translate)));o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect();}},[]);return null;}
