import Link from "next/link";
import CookiePreferencesLink from "@/components/CookiePreferencesLink";
export {default as Header} from "./Header";

function FacebookIcon(){return <svg className="socialIcon" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M22 12.06C22 6.5 17.52 2 12 2S2 6.5 2 12.06c0 5.02 3.66 9.18 8.44 9.94v-7.04H7.9v-2.9h2.54V9.84c0-2.52 1.49-3.91 3.77-3.91 1.09 0 2.23.2 2.23.2v2.46h-1.25c-1.24 0-1.63.77-1.63 1.56v1.91h2.77l-.44 2.9h-2.33V22C18.34 21.24 22 17.08 22 12.06Z"/></svg>}


export function Footer({showCta=true}:{showCta?:boolean}){return <>{showCta&&<section className="cta"><div className="wrap"><div><h2>Tem um projeto industrial em que podemos ajudar?</h2></div><Link className="button white" href="/contactos">Contacte-nos</Link></div></section>}<footer className="footer"><div className="wrap"><div className="foot"><div><img className="footerLogo" src="/images/logo-tamanho-eficaz.png" alt="Tamanho Eficaz"/><p>Manutenção industrial e indústria metalomecânica.</p><p>Atividade publicada em Portugal, Espanha, França e Bélgica.</p></div><div><h4>Empresa</h4><p><Link href="/empresa">Sobre nós</Link></p><p><Link href="/internacional">Internacional</Link></p><p><Link href="/noticias">Notícias</Link></p></div><div><h4>Soluções</h4><p><Link href="/servicos">Serviços</Link></p><p><Link href="/projetos">Projetos</Link></p><p><Link href="/trabalhe-connosco">Carreiras</Link></p></div><div><h4>Contactos</h4><p>+351 912 647 472</p><p>geral@tamanhoeficaz.pt</p><p>R. Mercado 26 R/C<br/>3020-863 Souselas</p><p><a className="facebookLink" href="https://www.facebook.com/TamanhoEficaz/" target="_blank" rel="noreferrer"><FacebookIcon/> Facebook</a></p></div></div><div className="legal"><span>© Tamanho Eficaz, Lda.</span><span><Link href="/privacidade">Privacidade</Link></span><span><Link href="/cookies">Cookies</Link></span><span><CookiePreferencesLink/></span><span><a href="https://channel.whistleon.com/tamanhoeficaz" target="_blank" rel="noreferrer">Canal de denúncias</a></span><span className="developerCredit">Site desenvolvido por{" "}<a href="https://www.facebook.com/marco.simoes.731" target="_blank" rel="noopener noreferrer"><strong>Marco Simões</strong></a></span></div></div></footer></>}
export function PageHero({kicker,title,text}:{kicker:string,title:string,text:string}){return <section className="pagehero"><div className="wrap"><div className="eyebrow light">{kicker}</div><h1>{title}</h1><p>{text}</p></div></section>}
