import Link from "next/link";
import {PageHero} from "@/components/Layout";
export default function P(){return <><PageHero kicker="Privacidade" title="Política de Privacidade" text="Informação sobre a forma como a Tamanho Eficaz trata dados pessoais através deste website."/><section className="section legalPage"><div className="wrap">
<p className="lead">A Tamanho Eficaz, Lda. respeita a privacidade dos utilizadores e trata os dados pessoais de acordo com o Regulamento Geral sobre a Proteção de Dados (RGPD), a Lei n.º 58/2019 e demais legislação aplicável.</p>
<h2>1. Responsável pelo tratamento</h2><p><strong>Tamanho Eficaz, Lda.</strong><br/>R. Mercado 26 R/C, 3020-863 Souselas, Portugal<br/>Telefone: +351 912 647 472<br/>E-mail: geral@tamanhoeficaz.pt</p>
<h2>2. Dados tratados e finalidades</h2><p>Podemos tratar os dados que o utilizador fornece nos formulários, designadamente nome, contactos, empresa, informação sobre projetos, área profissional, experiência, disponibilidade e ficheiros enviados. Os dados são utilizados para responder a contactos, analisar pedidos de proposta, gerir relações pré-contratuais ou comerciais e apreciar candidaturas de recrutamento.</p>
<h2>3. Fundamentos de licitude</h2><p>Consoante a situação, o tratamento pode basear-se em diligências pré-contratuais ou execução de contrato, cumprimento de obrigações legais, interesses legítimos da Tamanho Eficaz ou consentimento quando este seja o fundamento adequado. O envio de um formulário não constitui consentimento para comunicações de marketing.</p>
<h2>4. Candidaturas e currículos</h2><p>Os dados e documentos enviados para recrutamento são tratados exclusivamente para analisar a candidatura e contactar o candidato no âmbito de oportunidades profissionais. O candidato deve evitar incluir no currículo dados excessivos ou categorias especiais de dados que não sejam necessários à candidatura.</p>
<h2>5. Conservação</h2><p>Os dados são conservados apenas durante o período necessário às finalidades que justificaram a recolha e, quando aplicável, durante os prazos necessários ao cumprimento de obrigações legais, exercício ou defesa de direitos. Pedidos sem continuidade e candidaturas deixam de ser conservados quando já não exista finalidade legítima que justifique a sua manutenção.</p>
<h2>6. Destinatários e prestadores</h2><p>Os dados podem ser tratados por prestadores que apoiem a Tamanho Eficaz na operação técnica do website, alojamento, correio eletrónico, gestão documental ou outros serviços necessários, atuando nos termos legalmente aplicáveis. Os dados não são vendidos.</p>
<h2>7. Transferências internacionais</h2><p>Quando um prestador implique tratamento de dados fora do Espaço Económico Europeu, serão utilizados os mecanismos legalmente exigidos para assegurar um nível adequado de proteção, quando aplicável.</p>
<h2>8. Segurança</h2><p>São adotadas medidas técnicas e organizativas adequadas ao risco para proteger os dados contra acesso, alteração, divulgação, perda ou destruição não autorizados. Nenhum sistema ligado à Internet permite, contudo, garantir segurança absoluta.</p>
<h2>9. Direitos dos titulares</h2><p>Nos termos aplicáveis, o titular pode solicitar acesso, retificação, apagamento, limitação do tratamento, portabilidade e oposição, bem como retirar o consentimento a qualquer momento quando o tratamento se baseie nele, sem afetar a licitude do tratamento anteriormente realizado.</p><p>Para exercer direitos ou colocar uma questão sobre privacidade, contacte <strong>geral@tamanhoeficaz.pt</strong>. Poderá ser necessário confirmar a identidade do requerente antes de executar o pedido.</p>
<h2>10. Reclamação</h2><p>O titular pode apresentar reclamação à autoridade de controlo competente. Em Portugal, a autoridade é a Comissão Nacional de Proteção de Dados (CNPD).</p>
<h2>11. Cookies e serviços externos</h2><p>Consulte a nossa <Link href="/cookies">Política de Cookies</Link>. Ligações para serviços externos, como Facebook ou o canal de denúncias WhistleOn, conduzem a serviços com políticas próprias, pelas quais esses terceiros são responsáveis.</p>
<h2>12. Alterações</h2><p>Esta política pode ser atualizada para refletir alterações legais, técnicas ou nos tratamentos efetuados. A versão publicada nesta página é a versão em vigor.</p><p><strong>Última atualização: 30 de setembro de 2026.</strong></p>
</div></section></>}
